#!/bin/bash

deepspeed --master_port 23345 /LLava-LLama3/llava/train/train_mem.py \
    --deepspeed /LLava-LLama3/scripts/zero3.json \
    --model_name_or_path /LLava-LLama3/checkpoints/DeepSeek-R1-Distill-Llama-8B \
    --version llama3 \
    --data_path /LLava-LLama3/playground/data/llava_v1_5_mix665k_unid.json \
    --image_folder /LLava-LLama3/playground/data \
    --vision_tower /LLava-LLama3/checkpoints/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /LLava-LLama3/results/llava_deepseek_v1_5_8b_pretrain/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /LLava-LLama3/results/llava_deepseek_v1_5_8b_finetune \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
